<?php $this->headTitle('Add User') ?>
<?=$this->flashMessenger()->render(); ?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
	'form' 			=> $this->form,
	'formName'		=> 'User',
    'postUrl'		=> $this->url('admin/user/edit', [
        'action'    => 'add',
    ]),
    'cancelUrl'     => $this->url('admin/user'),
	'formElements'	=> [
		'firstname', 'lastname', 'email', 'passwd',
        'passwd-confirm', 'role', 'security'
	],
]); ?>