<?php $this->headTitle('Edit User') ?>
<?php $this->layout()->pageTitle = $this->translate('Edit User');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<a class="btn btn-default" href="<?=$this->url('admin/user/edit', [
    'action' => 'reset-password',
    'id'     => $this->model->getUserId(),
]);?>" data-toggle="tooltip" title="<?=$this->translate('Reset Password');?>"><?=$this->translate('Reset Password');?></a>
<button type="submit" form="form-user" data-toggle="tooltip" title="<?=$this->translate('Save');?>" class="btn btn-primary">
    <i class="fa fa-save"></i>
</button>
<a href="<?=$this->url('admin/user');?>" data-toggle="tooltip" title="<?=$this->translate('Cancel');?>" class="btn btn-default">
    <i class="fa fa-reply"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-user',
    'action' => $this->url('admin/user/edit', [
        'id' => $this->model->getUserId(),
    ]),
]); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> <?=$this->translate('Edit User');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->form($this->form);?>
    </div>
</div>
