<?php $this->headTitle('Users') ?>
<?php $this->layout()->pageTitle = $this->translate('Users');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<a href="<?=$this->url('admin/user', [
    'action' => 'add'
]);?>" type="submit" form="form-user" data-toggle="tooltip" title="<?=$this->translate('Add User');?>" class="btn btn-primary">
    <i class="fa fa-plus"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-list"></i> <?=$this->translate('User List');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->partial('uthando-admin/partial/search', [
            'name'			=> 'user',
            'searchInputs'	=> [
                $this->translate('Email') => 'email',
                $this->translate('User') => 'firstname-lastname',
            ],
        ]);?>
    </div>
    <div id="table-user" class="admin-table">
        <?=$this->partial('uthando-user/admin/list', [
            'models' => $this->models
        ]); ?>
    </div>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-user').dataGrid({
    	url : 'user/list',
    	query: { sort : 'name' },
    	searchForm : $('#search-user'),
    	paging : 'links',
    	columnSort: true
	});
});
<?php $this->inlineScript()->captureEnd(); ?>
