
<?=$this->partial('uthando-admin/partial/search', [
	'name'			=> 'user',
	'searchInputs'	=> [
		'Email' => 'email',
        'User'  => 'firstname-lastname',
	],
]);?>

<div id="table-user">
	<?=$this->partial('uthando-user/admin/list', [
	    'models' => $this->models
	]); ?>
</div>


<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-user').dataGrid({
    	url : 'user/list',
    	query: { sort : 'name' },
    	searchForm : $('#search-user'),
    	paging : 'links',
    	columnSort: true
	});
});
<?php $this->inlineScript()->captureEnd(); ?>
