<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'uthando-user/admin/add'                 => __DIR__ . '/view/uthando-user/admin/add.phtml',
    'uthando-user/admin/edit'                => __DIR__ . '/view/uthando-user/admin/edit.phtml',
    'uthando-user/admin/index'               => __DIR__ . '/view/uthando-user/admin/index.phtml',
    'uthando-user/admin/list'                => __DIR__ . '/view/uthando-user/admin/list.phtml',
    'uthando-user/email/layout'              => __DIR__ . '/view/uthando-user/email/layout.phtml',
    'uthando-user/email/register'            => __DIR__ . '/view/uthando-user/email/register.phtml',
    'uthando-user/email/reset-password'      => __DIR__ . '/view/uthando-user/email/reset-password.phtml',
    'uthando-user/email/verify'              => __DIR__ . '/view/uthando-user/email/verify.phtml',
    'uthando-user/registration/verify-email' => __DIR__ . '/view/uthando-user/registration/verify-email.phtml',
    'uthando-user/settings/index'            => __DIR__ . '/view/uthando-user/settings/index.phtml',
    'uthando-user/user/edit'                 => __DIR__ . '/view/uthando-user/user/edit.phtml',
    'uthando-user/user/forgot-password'      => __DIR__ . '/view/uthando-user/user/forgot-password.phtml',
    'uthando-user/user/login-form'           => __DIR__ . '/view/uthando-user/user/login-form.phtml',
    'uthando-user/user/login'                => __DIR__ . '/view/uthando-user/user/login.phtml',
    'uthando-user/user/password'             => __DIR__ . '/view/uthando-user/user/password.phtml',
    'uthando-user/user/register'             => __DIR__ . '/view/uthando-user/user/register.phtml',
    'uthando-user/user/thank-you'            => __DIR__ . '/view/uthando-user/user/thank-you.phtml',
    'uthando-user/user/user-form'            => __DIR__ . '/view/uthando-user/user/user-form.phtml',
);
