
<?php 
$form = $this->form;
$email = $form->get('email');
$passwd = $form->get('passwd');
?>

<div class="row">
    <form class="col-md-12 form-horizontal"  method="post" action="<?=$this->url('user', [
    	'action' => 'authenticate',
    ]) ?>">
        <fieldset>
            <legend><?=$this->legend;?></legend>
            <div class="form-group<?php if ($email->getMessages()) echo ' has-error'; ?>">
                <label class="col-md-2 control-label" for="email">Email:</label>
                <div class="col-md-4">
                    
                    <?=$this->formEmail($email->setAttribute('class', 'form-control')); ?>
                    <span class="help-block">
                    <?=$this->formElementErrors($email, array(
                        'class' => 'list-unstyled'
                    )); ?>
                    </span>
                </div>
            </div>
            
            <div class="form-group<?php if ($passwd->getMessages()) echo ' has-error'; ?>">
                <label class="col-md-2 control-label" for="passwd">Password:</label>
                <div class="col-md-4">
                    <?=$this->formPassword($passwd->setAttribute('class', 'form-control')); ?>
                    <span class="help-block">
                    <?=$this->formElementErrors($passwd, array(
                        'class' => 'list-unstyled'
                    )); ?>
                    </span>
                </div>
            </div>
            
            <?=$this->formElement($form->get('security')); ?>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary" 
                    data-loading-text="Please wait...">Login</button>
                </div>
            </div>
        </fieldset>
        
        <?=$this->formElement($form->get('returnTo')); ?>
        
    </form>
</div>
    