
<?php 
$form = $this->form;
$email = $form->get('email');
$passwd = $form->get('passwd');
?>

<form class="form-horizontal"  method="post" action="<?=$this->url('user', [
	'action' => 'authenticate',
]) ?>">
    <fieldset>
    <legend><?=$this->legend;?></legend>
    <div class="control-group<?php if ($email->getMessages()) echo ' error'; ?>">
        <label class="control-label" for="email">Email:</label>
        <div class="controls">
            <div class="input-prepend">
                <span class="add-on"><i class="icon-envelope"></i></span>
                <?=$this->formEmail($email); ?>
            </div>
            <span class="help-block">
            <?=$this->formElementErrors($email, array(
                'class' => 'unstyled'
            )); ?>
            </span>
        </div>
    </div>
    <div class="control-group<?php if ($passwd->getMessages()) echo ' error'; ?>">
        <label class="control-label" for="passwd">Password:</label>
        <div class="controls">
            <div class="input-prepend">
                <span class="add-on"><i class="icon-lock"></i></span>
                <?=$this->formPassword($passwd); ?>
            </div>
            <span class="help-block">
            <?=$this->formElementErrors($passwd, array(
                'class' => 'unstyled'
            )); ?>
            </span>
        </div>
    </div>
    <?=$this->formElement($form->get('security')); ?>
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn btn-primary" 
            data-loading-text="Please wait...">Login</button>
        </div>
    </div>
    </fieldset>
    
    <?=$this->formElement($form->get('returnTo')); ?>
    
</form>
    