<?php $this->headTitle('Log In') ?>

<?php $this->loginForm->setAttributes([
    'method' => 'post',
    'action' => $this->url('user', [
        'action' => 'authenticate'
    ]),
]); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <?=$this->translate('Login');?>
            <span class="pull-right">
                <a href="<?=$this->url('user', [
                    'action' => 'forgot-password'
                ]);?>"><?=$this->translate('Forgot Password');?></a>
            </span>
        </h3>
    </div>
    <div class="panel-body">
        <?=$this->form($this->loginForm);?>
    </div>
</div>
