<?php $this->headTitle('Edit Password'); ?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'action' => $this->url('user', [
        'action' => 'password'
    ]),
]); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?=$this->translate('Edit Password');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->form($this->form);?>
    </div>
</div>
