<?php $this->headTitle('Edit Password'); ?>

<form class="form-horizontal"  method="post" action="<?php echo $this->url('user/default', [
	'action' => 'password'
]); ?>">
    <fieldset>
    <legend>Edit Password</legend>
    
    <div class="control-group<?php if ($this->form->get('passwd')->getMessages()) echo ' error'; ?>">
        <label class="control-label" for="title">Password:</label>
        <div class="controls">
            <?=$this->formPassword($this->form->get('passwd')); ?>
            <label class="checkbox inline">
            	<input type="checkbox" id="showPassword"> Show Password
            </label>
            <span class="help-block">
            <?=$this->formElementErrors($this->form->get('passwd'), array(
                'class' => 'unstyled'
            )); ?>
            </span>
        </div>
    </div>
    
    <div class="control-group<?php if ($this->form->get('passwd-confirm')->getMessages()) echo ' error'; ?>">
        <label class="control-label" for="title">Confirm Password:</label>
        <div class="controls">
            <?=$this->formPassword($this->form->get('passwd-confirm')); ?>
            <span class="help-block">
            <?=$this->formElementErrors($this->form->get('passwd-confirm'), array(
                'class' => 'unstyled'
            )); ?>
            </span>
        </div>
    </div>
   	
    <input type="hidden" name="action" value="password">
    
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn btn-primary" 
            data-loading-text="Please wait...">Submit</button>
            <button type="button" class="btn btn-warning" 
            data-loading-text="Please wait..." onClick="window.location = '<?=$this->url('user/default'); ?>';">Cancel</button>
        </div>
    </div>
    </fieldset>
    
</form>


