<?php $this->headTitle('Edit Password'); ?>

<div class="row">
    <form class="col-md-12 form-horizontal"  method="post" action="<?php echo $this->url('user', [
    	'action' => 'password'
    ]); ?>">
        <fieldset>
            <legend>Edit Password</legend>
            
            <div class="form-group<?php if ($this->form->get('passwd')->getMessages()) echo ' has-error'; ?>">
                <label class="col-md-2 control-label" for="title">Password:</label>
                <div class="col-md-4">
                    <?=$this->formPassword($this->form->get('passwd')->setAttribute('class', 'form-control')); ?>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" id="showPassword"> Show Password
                        </label>
                    </div>
                    <span class="help-block">
                    <?=$this->formElementErrors($this->form->get('passwd'), array(
                        'class' => 'list-unstyled'
                    )); ?>
                    </span>
                </div>
            </div>
            
            <div class="form-group<?php if ($this->form->get('passwd-confirm')->getMessages()) echo ' has-error'; ?>">
                <label class="col-md-2 control-label" for="title">Confirm Password:</label>
                <div class="col-md-4">
                    <?=$this->formPassword($this->form->get('passwd-confirm')->setAttribute('class', 'form-control')); ?>
                    <span class="help-block">
                    <?=$this->formElementErrors($this->form->get('passwd-confirm'), array(
                        'class' => 'list-unstyled'
                    )); ?>
                    </span>
                </div>
            </div>
           	
            <input type="hidden" name="action" value="password">
            
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary" 
                    data-loading-text="Please wait...">Submit</button>
                    <button type="button" class="btn btn-warning" 
                    data-loading-text="Please wait..." onClick="window.location = '<?=$this->url('user'); ?>';">Cancel</button>
                </div>
            </div>
        </fieldset>
        
    </form>
</div>

