<?php $this->headTitle('Register') ?>

<?php $this->registerForm->setAttributes([
	'method' => 'post',
	'action' => $this->url('user', [
		'action' => 'register'
	]),
]); ?>

<div class="col-md-6 col-md-offset-3">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Register</h3>
		</div>
		<div class="panel-body">
			<?=$this->form($this->registerForm);?>
		</div>
	</div>
</div>
