<?php
$form = $this->form;
$routeArray = ['action' => $this->formAction];
?>
<div class="row">
    <form class="col-sm-12 form-horizontal"  method="post" action="<?=$this->url('user', $routeArray) ?>">
        <fieldset>
            <legend><?=$this->legend; ?> </legend>
            <div class="form-group<?php if ($form->get('firstname')->getMessages()) echo ' has-error'; ?>">
                <label class="col-sm-2 control-label" for="title">Forename:</label>
                <div class="col-sm-4">
                    <?=$this->formInput($form->get('firstname')->setAttribute('class', 'form-control')); ?>
                    <span class="help-block">
                    <?=$this->formElementErrors($form->get('firstname'), array(
                        'class' => 'list-unstyled'
                    )); ?>
                    </span>
                </div>
            </div>
            
            <div class="form-group<?php if ($form->get('lastname')->getMessages()) echo ' has-error'; ?>">
                <label class="col-sm-2 control-label" for="title">Surname:</label>
                <div class="col-sm-4">
                    <?=$this->formInput($form->get('lastname')->setAttribute('class', 'form-control')); ?>
                    <span class="help-block">
                    <?=$this->formElementErrors($form->get('lastname'), [
                        'class' => 'list-unstyled'
                    ]); ?>
                    </span>
                </div>
            </div>
            
            <div class="form-group<?php if ($form->get('email')->getMessages()) echo ' has-error'; ?>">
                <label class="col-sm-2 control-label" for="title">Email:</label>
                <div class="col-sm-4">
                    <?=$this->formEmail($form->get('email')->setAttribute('class', 'form-control')); ?>
                    <span class="help-block">
                    <?=$this->formElementErrors($form->get('email'), [
                        'class' => 'listunstyled'
                    ]); ?>
                    </span>
                </div>
            </div>
            
            <?php if($this->formAction === 'add' || $this->formAction === 'register'):?>
            <div class="form-group<?php if ($form->get('passwd')->getMessages()) echo ' has-error'; ?>">
                <label class="col-sm-2 control-label" for="title">Password:</label>
                <div class="col-sm-4">
                    <?=$this->formPassword($form->get('passwd')->setAttribute('class', 'form-control')); ?>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" id="showPassword"> Show Password
                        </label>
                    </div>
                    <span class="help-block">
                    <?=$this->formElementErrors($form->get('passwd'), [
                        'class' => 'list-unstyled'
                    ]); ?>
                    </span>
                </div>
            </div>
            
            <div class="form-group<?php if ($form->get('passwd-confirm')->getMessages()) echo ' has-error'; ?>">
                <label class="col-sm-2 control-label" for="title">Confirm Password:</label>
                <div class="col-sm-4">
                    <?=$this->formPassword($form->get('passwd-confirm')->setAttribute('class', 'form-control')); ?>
                    <span class="help-block">
                    <?=$this->formElementErrors($form->get('passwd-confirm'), [
                        'class' => 'list-unstyled'
                    ]); ?>
                    </span>
                </div>
            </div>
            <?php endif;?>
            
            <?=$this->formElement($form->get('userId')); ?>
           	
            <input type="hidden" name="action" value="<?=$this->formAction; ?>">
            
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary" 
                    data-loading-text="Please wait...">Submit</button>
                    <button type="button" class="btn btn-warning" 
                    data-loading-text="Please wait..." onClick="window.location = '<?=$this->url('home') ?>';">Cancel</button>
                </div>
            </div>
        </fieldset>
        
        <?=$this->formElement($form->get('returnTo')); ?>
    </form>
</div>


