
<?php if ($this->result):?>
    <h2>Email Verification Passed</h2>
    <p>You can now login in with the password and email address you signed up with.</p>
    <a href="<?=$this->url('user', [
        'action' => 'login',
    ]);?>" class="btn btn-primary">Login</a>
<?php else:?>
    <h2>Email Verification Failed.</h2>
    <p>Please contact support on <?=$this->contact('details.phone');?> for help.</p>
<?php endif;?>
