
<?php /* @var $user \UthandoUser\Model\UserModel */ ?>
<?php $user = $this->user; ?>
<h2>Reset Password Request From <?=$this->contact('details.name');?></h2>

<p>Dear <?=$user->getFullName();?>,</p>
<p>We have received a reset password request from you.</p>
<p>If you did not make this request please contact us immediately on <?=$this->contact('details.phone');?></p>

<p>Your new Password is:</p>
<p><?=$user->getPasswd();?>

<p>Please login with this new password, once loggin you can change it to something more memorable</p>